-- Wolfhouse Somo seed — generated from Airtable CSV exports
-- Re-run: node scripts/generate-seed.js
BEGIN;

INSERT INTO clients (id, slug, name, timezone, currency, settings)
VALUES (
  'a0000000-0000-4000-8000-000000000001',
  'wolfhouse-somo',
  'Wolfhouse Surf Camp Somo',
  'Europe/Madrid',
  'EUR',
  '{"website":"https://www.wolf-house.com/surfcampsomo","airtable_base_id":"appOCWIN47Bui9CSS"}'::jsonb
) ON CONFLICT (slug) DO NOTHING;

INSERT INTO packages (client_id, code, name, deposit_amount_cents, metadata)
SELECT id, v.code, v.name, v.deposit, '{}'::jsonb
FROM clients, (VALUES
  ('malibu', 'Malibu', 20000),
  ('uluwatu', 'Uluwatu', 20000),
  ('waimea', 'Waimea', 20000),
  ('custom', 'Custom', NULL)
) AS v(code, name, deposit)
WHERE clients.slug = 'wolfhouse-somo'
ON CONFLICT (client_id, code) DO NOTHING;

INSERT INTO rooms (client_id, room_code, capacity, fill_priority, private_priority, gender_strategy, can_be_matrimonial, often_used_by_operator, active, room_type) SELECT id, 'R1', 5, 2, 5, 'Flexible', FALSE, FALSE, TRUE, NULL FROM clients WHERE slug = 'wolfhouse-somo' ON CONFLICT (client_id, room_code) DO NOTHING;
INSERT INTO rooms (client_id, room_code, capacity, fill_priority, private_priority, gender_strategy, can_be_matrimonial, often_used_by_operator, active, room_type) SELECT id, 'R2', 5, 3, 5, 'Male preferred', FALSE, FALSE, TRUE, NULL FROM clients WHERE slug = 'wolfhouse-somo' ON CONFLICT (client_id, room_code) DO NOTHING;
INSERT INTO rooms (client_id, room_code, capacity, fill_priority, private_priority, gender_strategy, can_be_matrimonial, often_used_by_operator, active, room_type) SELECT id, 'R3', 4, 1, 2, 'Flexible', TRUE, FALSE, TRUE, NULL FROM clients WHERE slug = 'wolfhouse-somo' ON CONFLICT (client_id, room_code) DO NOTHING;
INSERT INTO rooms (client_id, room_code, capacity, fill_priority, private_priority, gender_strategy, can_be_matrimonial, often_used_by_operator, active, room_type) SELECT id, 'R4', 9, 9, 9, 'Mixed ok', FALSE, FALSE, TRUE, NULL FROM clients WHERE slug = 'wolfhouse-somo' ON CONFLICT (client_id, room_code) DO NOTHING;
INSERT INTO rooms (client_id, room_code, capacity, fill_priority, private_priority, gender_strategy, can_be_matrimonial, often_used_by_operator, active, room_type) SELECT id, 'R5', 6, 4, 6, 'Female preferred', FALSE, FALSE, TRUE, NULL FROM clients WHERE slug = 'wolfhouse-somo' ON CONFLICT (client_id, room_code) DO NOTHING;
INSERT INTO rooms (client_id, room_code, capacity, fill_priority, private_priority, gender_strategy, can_be_matrimonial, often_used_by_operator, active, room_type) SELECT id, 'R6', 2, 99, 1, 'Private', TRUE, FALSE, TRUE, 'Private-Only' FROM clients WHERE slug = 'wolfhouse-somo' ON CONFLICT (client_id, room_code) DO NOTHING;
INSERT INTO rooms (client_id, room_code, capacity, fill_priority, private_priority, gender_strategy, can_be_matrimonial, often_used_by_operator, active, room_type) SELECT id, 'R7', 4, 5, 3, 'Flexible', FALSE, TRUE, TRUE, NULL FROM clients WHERE slug = 'wolfhouse-somo' ON CONFLICT (client_id, room_code) DO NOTHING;
INSERT INTO rooms (client_id, room_code, capacity, fill_priority, private_priority, gender_strategy, can_be_matrimonial, often_used_by_operator, active, room_type) SELECT id, 'R8', 5, 6, 5, 'Female preferred', FALSE, FALSE, TRUE, NULL FROM clients WHERE slug = 'wolfhouse-somo' ON CONFLICT (client_id, room_code) DO NOTHING;
INSERT INTO rooms (client_id, room_code, capacity, fill_priority, private_priority, gender_strategy, can_be_matrimonial, often_used_by_operator, active, room_type) SELECT id, 'R9', 6, 7, 6, 'Flexible', FALSE, TRUE, TRUE, NULL FROM clients WHERE slug = 'wolfhouse-somo' ON CONFLICT (client_id, room_code) DO NOTHING;
INSERT INTO rooms (client_id, room_code, capacity, fill_priority, private_priority, gender_strategy, can_be_matrimonial, often_used_by_operator, active, room_type) SELECT id, 'R10', 6, 8, 6, 'Flexible', FALSE, TRUE, TRUE, NULL FROM clients WHERE slug = 'wolfhouse-somo' ON CONFLICT (client_id, room_code) DO NOTHING;

INSERT INTO beds (client_id, room_id, bed_code, bed_number, bed_label, planning_row_label, active, sellable) SELECT c.id, r.id, 'R1-B1', 1, 'Bed 1', 'R1 - Bed 1', TRUE, TRUE FROM clients c JOIN rooms r ON r.client_id = c.id AND r.room_code = 'R1' WHERE c.slug = 'wolfhouse-somo' ON CONFLICT (client_id, bed_code) DO NOTHING;
INSERT INTO beds (client_id, room_id, bed_code, bed_number, bed_label, planning_row_label, active, sellable) SELECT c.id, r.id, 'R1-B2', 2, 'Bed 2', 'R1 - Bed 2', TRUE, TRUE FROM clients c JOIN rooms r ON r.client_id = c.id AND r.room_code = 'R1' WHERE c.slug = 'wolfhouse-somo' ON CONFLICT (client_id, bed_code) DO NOTHING;
INSERT INTO beds (client_id, room_id, bed_code, bed_number, bed_label, planning_row_label, active, sellable) SELECT c.id, r.id, 'R1-B3', 3, 'Bed 3', 'R1 - Bed 3', TRUE, TRUE FROM clients c JOIN rooms r ON r.client_id = c.id AND r.room_code = 'R1' WHERE c.slug = 'wolfhouse-somo' ON CONFLICT (client_id, bed_code) DO NOTHING;
INSERT INTO beds (client_id, room_id, bed_code, bed_number, bed_label, planning_row_label, active, sellable) SELECT c.id, r.id, 'R1-B4', 4, 'Bed 4', 'R1 - Bed 4', TRUE, TRUE FROM clients c JOIN rooms r ON r.client_id = c.id AND r.room_code = 'R1' WHERE c.slug = 'wolfhouse-somo' ON CONFLICT (client_id, bed_code) DO NOTHING;
INSERT INTO beds (client_id, room_id, bed_code, bed_number, bed_label, planning_row_label, active, sellable) SELECT c.id, r.id, 'R1-B5', 5, 'Bed 5', 'R1 - Bed 5', TRUE, TRUE FROM clients c JOIN rooms r ON r.client_id = c.id AND r.room_code = 'R1' WHERE c.slug = 'wolfhouse-somo' ON CONFLICT (client_id, bed_code) DO NOTHING;
INSERT INTO beds (client_id, room_id, bed_code, bed_number, bed_label, planning_row_label, active, sellable) SELECT c.id, r.id, 'R2-B1', 1, 'Bed 1', 'R2 - Bed 1', TRUE, TRUE FROM clients c JOIN rooms r ON r.client_id = c.id AND r.room_code = 'R2' WHERE c.slug = 'wolfhouse-somo' ON CONFLICT (client_id, bed_code) DO NOTHING;
INSERT INTO beds (client_id, room_id, bed_code, bed_number, bed_label, planning_row_label, active, sellable) SELECT c.id, r.id, 'R2-B2', 2, 'Bed 2', 'R2 - Bed 2', TRUE, TRUE FROM clients c JOIN rooms r ON r.client_id = c.id AND r.room_code = 'R2' WHERE c.slug = 'wolfhouse-somo' ON CONFLICT (client_id, bed_code) DO NOTHING;
INSERT INTO beds (client_id, room_id, bed_code, bed_number, bed_label, planning_row_label, active, sellable) SELECT c.id, r.id, 'R2-B3', 3, 'Bed 3', 'R2 - Bed 3', TRUE, TRUE FROM clients c JOIN rooms r ON r.client_id = c.id AND r.room_code = 'R2' WHERE c.slug = 'wolfhouse-somo' ON CONFLICT (client_id, bed_code) DO NOTHING;
INSERT INTO beds (client_id, room_id, bed_code, bed_number, bed_label, planning_row_label, active, sellable) SELECT c.id, r.id, 'R2-B4', 4, 'Bed 4', 'R2 - Bed 4', TRUE, TRUE FROM clients c JOIN rooms r ON r.client_id = c.id AND r.room_code = 'R2' WHERE c.slug = 'wolfhouse-somo' ON CONFLICT (client_id, bed_code) DO NOTHING;
INSERT INTO beds (client_id, room_id, bed_code, bed_number, bed_label, planning_row_label, active, sellable) SELECT c.id, r.id, 'R2-B5', 5, 'Bed 5', 'R2 - Bed 5', TRUE, TRUE FROM clients c JOIN rooms r ON r.client_id = c.id AND r.room_code = 'R2' WHERE c.slug = 'wolfhouse-somo' ON CONFLICT (client_id, bed_code) DO NOTHING;
INSERT INTO beds (client_id, room_id, bed_code, bed_number, bed_label, planning_row_label, active, sellable) SELECT c.id, r.id, 'R3-B1', 1, 'Bed 1', 'R3 - Bed 1', TRUE, TRUE FROM clients c JOIN rooms r ON r.client_id = c.id AND r.room_code = 'R3' WHERE c.slug = 'wolfhouse-somo' ON CONFLICT (client_id, bed_code) DO NOTHING;
INSERT INTO beds (client_id, room_id, bed_code, bed_number, bed_label, planning_row_label, active, sellable) SELECT c.id, r.id, 'R3-B2', 2, 'Bed 2', 'R3 - Bed 2', TRUE, TRUE FROM clients c JOIN rooms r ON r.client_id = c.id AND r.room_code = 'R3' WHERE c.slug = 'wolfhouse-somo' ON CONFLICT (client_id, bed_code) DO NOTHING;
INSERT INTO beds (client_id, room_id, bed_code, bed_number, bed_label, planning_row_label, active, sellable) SELECT c.id, r.id, 'R3-B3', 3, 'Bed 3', 'R3 - Bed 3', TRUE, TRUE FROM clients c JOIN rooms r ON r.client_id = c.id AND r.room_code = 'R3' WHERE c.slug = 'wolfhouse-somo' ON CONFLICT (client_id, bed_code) DO NOTHING;
INSERT INTO beds (client_id, room_id, bed_code, bed_number, bed_label, planning_row_label, active, sellable) SELECT c.id, r.id, 'R3-B4', 4, 'Bed 4', 'R3 - Bed 4', TRUE, TRUE FROM clients c JOIN rooms r ON r.client_id = c.id AND r.room_code = 'R3' WHERE c.slug = 'wolfhouse-somo' ON CONFLICT (client_id, bed_code) DO NOTHING;
INSERT INTO beds (client_id, room_id, bed_code, bed_number, bed_label, planning_row_label, active, sellable) SELECT c.id, r.id, 'R4-B1', 1, 'Bed 1', 'R4 - Bed 1', TRUE, TRUE FROM clients c JOIN rooms r ON r.client_id = c.id AND r.room_code = 'R4' WHERE c.slug = 'wolfhouse-somo' ON CONFLICT (client_id, bed_code) DO NOTHING;
INSERT INTO beds (client_id, room_id, bed_code, bed_number, bed_label, planning_row_label, active, sellable) SELECT c.id, r.id, 'R4-B2', 2, 'Bed 2', 'R4 - Bed 2', TRUE, TRUE FROM clients c JOIN rooms r ON r.client_id = c.id AND r.room_code = 'R4' WHERE c.slug = 'wolfhouse-somo' ON CONFLICT (client_id, bed_code) DO NOTHING;
INSERT INTO beds (client_id, room_id, bed_code, bed_number, bed_label, planning_row_label, active, sellable) SELECT c.id, r.id, 'R4-B3', 3, 'Bed 3', 'R4 - Bed 3', TRUE, TRUE FROM clients c JOIN rooms r ON r.client_id = c.id AND r.room_code = 'R4' WHERE c.slug = 'wolfhouse-somo' ON CONFLICT (client_id, bed_code) DO NOTHING;
INSERT INTO beds (client_id, room_id, bed_code, bed_number, bed_label, planning_row_label, active, sellable) SELECT c.id, r.id, 'R4-B4', 4, 'Bed 4', 'R4 - Bed 4', TRUE, TRUE FROM clients c JOIN rooms r ON r.client_id = c.id AND r.room_code = 'R4' WHERE c.slug = 'wolfhouse-somo' ON CONFLICT (client_id, bed_code) DO NOTHING;
INSERT INTO beds (client_id, room_id, bed_code, bed_number, bed_label, planning_row_label, active, sellable) SELECT c.id, r.id, 'R4-B5', 5, 'Bed 5', 'R4 - Bed 5', TRUE, TRUE FROM clients c JOIN rooms r ON r.client_id = c.id AND r.room_code = 'R4' WHERE c.slug = 'wolfhouse-somo' ON CONFLICT (client_id, bed_code) DO NOTHING;
INSERT INTO beds (client_id, room_id, bed_code, bed_number, bed_label, planning_row_label, active, sellable) SELECT c.id, r.id, 'R4-B6', 6, 'Bed 6', 'R4 - Bed 6', TRUE, TRUE FROM clients c JOIN rooms r ON r.client_id = c.id AND r.room_code = 'R4' WHERE c.slug = 'wolfhouse-somo' ON CONFLICT (client_id, bed_code) DO NOTHING;
INSERT INTO beds (client_id, room_id, bed_code, bed_number, bed_label, planning_row_label, active, sellable) SELECT c.id, r.id, 'R4-B7', 7, 'Bed 7', 'R4 - Bed 7', TRUE, TRUE FROM clients c JOIN rooms r ON r.client_id = c.id AND r.room_code = 'R4' WHERE c.slug = 'wolfhouse-somo' ON CONFLICT (client_id, bed_code) DO NOTHING;
INSERT INTO beds (client_id, room_id, bed_code, bed_number, bed_label, planning_row_label, active, sellable) SELECT c.id, r.id, 'R4-B8', 8, 'Bed 8', 'R4 - Bed 8', TRUE, TRUE FROM clients c JOIN rooms r ON r.client_id = c.id AND r.room_code = 'R4' WHERE c.slug = 'wolfhouse-somo' ON CONFLICT (client_id, bed_code) DO NOTHING;
INSERT INTO beds (client_id, room_id, bed_code, bed_number, bed_label, planning_row_label, active, sellable) SELECT c.id, r.id, 'R4-B9', 9, 'Bed 9', 'R4 - Bed 9', TRUE, TRUE FROM clients c JOIN rooms r ON r.client_id = c.id AND r.room_code = 'R4' WHERE c.slug = 'wolfhouse-somo' ON CONFLICT (client_id, bed_code) DO NOTHING;
INSERT INTO beds (client_id, room_id, bed_code, bed_number, bed_label, planning_row_label, active, sellable) SELECT c.id, r.id, 'R5-B1', 1, 'Bed 1', 'R5 - Bed 1', TRUE, TRUE FROM clients c JOIN rooms r ON r.client_id = c.id AND r.room_code = 'R5' WHERE c.slug = 'wolfhouse-somo' ON CONFLICT (client_id, bed_code) DO NOTHING;
INSERT INTO beds (client_id, room_id, bed_code, bed_number, bed_label, planning_row_label, active, sellable) SELECT c.id, r.id, 'R5-B2', 2, 'Bed 2', 'R5 - Bed 2', TRUE, TRUE FROM clients c JOIN rooms r ON r.client_id = c.id AND r.room_code = 'R5' WHERE c.slug = 'wolfhouse-somo' ON CONFLICT (client_id, bed_code) DO NOTHING;
INSERT INTO beds (client_id, room_id, bed_code, bed_number, bed_label, planning_row_label, active, sellable) SELECT c.id, r.id, 'R5-B3', 3, 'Bed 3', 'R5 - Bed 3', TRUE, TRUE FROM clients c JOIN rooms r ON r.client_id = c.id AND r.room_code = 'R5' WHERE c.slug = 'wolfhouse-somo' ON CONFLICT (client_id, bed_code) DO NOTHING;
INSERT INTO beds (client_id, room_id, bed_code, bed_number, bed_label, planning_row_label, active, sellable) SELECT c.id, r.id, 'R5-B4', 4, 'Bed 4', 'R5 - Bed 4', TRUE, TRUE FROM clients c JOIN rooms r ON r.client_id = c.id AND r.room_code = 'R5' WHERE c.slug = 'wolfhouse-somo' ON CONFLICT (client_id, bed_code) DO NOTHING;
INSERT INTO beds (client_id, room_id, bed_code, bed_number, bed_label, planning_row_label, active, sellable) SELECT c.id, r.id, 'R5-B5', 5, 'Bed 5', 'R5 - Bed 5', TRUE, TRUE FROM clients c JOIN rooms r ON r.client_id = c.id AND r.room_code = 'R5' WHERE c.slug = 'wolfhouse-somo' ON CONFLICT (client_id, bed_code) DO NOTHING;
INSERT INTO beds (client_id, room_id, bed_code, bed_number, bed_label, planning_row_label, active, sellable) SELECT c.id, r.id, 'R5-B6', 6, 'Bed 6', 'R5 - Bed 6', TRUE, TRUE FROM clients c JOIN rooms r ON r.client_id = c.id AND r.room_code = 'R5' WHERE c.slug = 'wolfhouse-somo' ON CONFLICT (client_id, bed_code) DO NOTHING;
INSERT INTO beds (client_id, room_id, bed_code, bed_number, bed_label, planning_row_label, active, sellable) SELECT c.id, r.id, 'R6-B1', 1, 'Bed 1', 'R6 - Bed 1', TRUE, TRUE FROM clients c JOIN rooms r ON r.client_id = c.id AND r.room_code = 'R6' WHERE c.slug = 'wolfhouse-somo' ON CONFLICT (client_id, bed_code) DO NOTHING;
INSERT INTO beds (client_id, room_id, bed_code, bed_number, bed_label, planning_row_label, active, sellable) SELECT c.id, r.id, 'R6-B2', 2, 'Bed 2', 'R6 - Bed 2', TRUE, TRUE FROM clients c JOIN rooms r ON r.client_id = c.id AND r.room_code = 'R6' WHERE c.slug = 'wolfhouse-somo' ON CONFLICT (client_id, bed_code) DO NOTHING;
INSERT INTO beds (client_id, room_id, bed_code, bed_number, bed_label, planning_row_label, active, sellable) SELECT c.id, r.id, 'R7-B1', 1, 'Bed 1', 'R7 - Bed 1', TRUE, TRUE FROM clients c JOIN rooms r ON r.client_id = c.id AND r.room_code = 'R7' WHERE c.slug = 'wolfhouse-somo' ON CONFLICT (client_id, bed_code) DO NOTHING;
INSERT INTO beds (client_id, room_id, bed_code, bed_number, bed_label, planning_row_label, active, sellable) SELECT c.id, r.id, 'R7-B2', 2, 'Bed 2', 'R7 - Bed 2', TRUE, TRUE FROM clients c JOIN rooms r ON r.client_id = c.id AND r.room_code = 'R7' WHERE c.slug = 'wolfhouse-somo' ON CONFLICT (client_id, bed_code) DO NOTHING;
INSERT INTO beds (client_id, room_id, bed_code, bed_number, bed_label, planning_row_label, active, sellable) SELECT c.id, r.id, 'R7-B3', 3, 'Bed 3', 'R7 - Bed 3', TRUE, TRUE FROM clients c JOIN rooms r ON r.client_id = c.id AND r.room_code = 'R7' WHERE c.slug = 'wolfhouse-somo' ON CONFLICT (client_id, bed_code) DO NOTHING;
INSERT INTO beds (client_id, room_id, bed_code, bed_number, bed_label, planning_row_label, active, sellable) SELECT c.id, r.id, 'R7-B4', 4, 'Bed 4', 'R7 - Bed 4', TRUE, TRUE FROM clients c JOIN rooms r ON r.client_id = c.id AND r.room_code = 'R7' WHERE c.slug = 'wolfhouse-somo' ON CONFLICT (client_id, bed_code) DO NOTHING;
INSERT INTO beds (client_id, room_id, bed_code, bed_number, bed_label, planning_row_label, active, sellable) SELECT c.id, r.id, 'R8-B1', 1, 'Bed 1', 'R8 - Bed 1', TRUE, TRUE FROM clients c JOIN rooms r ON r.client_id = c.id AND r.room_code = 'R8' WHERE c.slug = 'wolfhouse-somo' ON CONFLICT (client_id, bed_code) DO NOTHING;
INSERT INTO beds (client_id, room_id, bed_code, bed_number, bed_label, planning_row_label, active, sellable) SELECT c.id, r.id, 'R8-B2', 2, 'Bed 2', 'R8 - Bed 2', TRUE, TRUE FROM clients c JOIN rooms r ON r.client_id = c.id AND r.room_code = 'R8' WHERE c.slug = 'wolfhouse-somo' ON CONFLICT (client_id, bed_code) DO NOTHING;
INSERT INTO beds (client_id, room_id, bed_code, bed_number, bed_label, planning_row_label, active, sellable) SELECT c.id, r.id, 'R8-B3', 3, 'Bed 3', 'R8 - Bed 3', TRUE, TRUE FROM clients c JOIN rooms r ON r.client_id = c.id AND r.room_code = 'R8' WHERE c.slug = 'wolfhouse-somo' ON CONFLICT (client_id, bed_code) DO NOTHING;
INSERT INTO beds (client_id, room_id, bed_code, bed_number, bed_label, planning_row_label, active, sellable) SELECT c.id, r.id, 'R8-B4', 4, 'Bed 4', 'R8 - Bed 4', TRUE, TRUE FROM clients c JOIN rooms r ON r.client_id = c.id AND r.room_code = 'R8' WHERE c.slug = 'wolfhouse-somo' ON CONFLICT (client_id, bed_code) DO NOTHING;
INSERT INTO beds (client_id, room_id, bed_code, bed_number, bed_label, planning_row_label, active, sellable) SELECT c.id, r.id, 'R8-B5', 5, 'Bed 5', 'R8 - Bed 5', TRUE, TRUE FROM clients c JOIN rooms r ON r.client_id = c.id AND r.room_code = 'R8' WHERE c.slug = 'wolfhouse-somo' ON CONFLICT (client_id, bed_code) DO NOTHING;
INSERT INTO beds (client_id, room_id, bed_code, bed_number, bed_label, planning_row_label, active, sellable) SELECT c.id, r.id, 'R9-B1', 1, 'Bed 1', 'R9 - Bed 1', TRUE, TRUE FROM clients c JOIN rooms r ON r.client_id = c.id AND r.room_code = 'R9' WHERE c.slug = 'wolfhouse-somo' ON CONFLICT (client_id, bed_code) DO NOTHING;
INSERT INTO beds (client_id, room_id, bed_code, bed_number, bed_label, planning_row_label, active, sellable) SELECT c.id, r.id, 'R9-B2', 2, 'Bed 2', 'R9 - Bed 2', TRUE, TRUE FROM clients c JOIN rooms r ON r.client_id = c.id AND r.room_code = 'R9' WHERE c.slug = 'wolfhouse-somo' ON CONFLICT (client_id, bed_code) DO NOTHING;
INSERT INTO beds (client_id, room_id, bed_code, bed_number, bed_label, planning_row_label, active, sellable) SELECT c.id, r.id, 'R9-B3', 3, 'Bed 3', 'R9 - Bed 3', TRUE, TRUE FROM clients c JOIN rooms r ON r.client_id = c.id AND r.room_code = 'R9' WHERE c.slug = 'wolfhouse-somo' ON CONFLICT (client_id, bed_code) DO NOTHING;
INSERT INTO beds (client_id, room_id, bed_code, bed_number, bed_label, planning_row_label, active, sellable) SELECT c.id, r.id, 'R9-B4', 4, 'Bed 4', 'R9 - Bed 4', TRUE, TRUE FROM clients c JOIN rooms r ON r.client_id = c.id AND r.room_code = 'R9' WHERE c.slug = 'wolfhouse-somo' ON CONFLICT (client_id, bed_code) DO NOTHING;
INSERT INTO beds (client_id, room_id, bed_code, bed_number, bed_label, planning_row_label, active, sellable) SELECT c.id, r.id, 'R9-B5', 5, 'Bed 5', 'R9 - Bed 5', TRUE, TRUE FROM clients c JOIN rooms r ON r.client_id = c.id AND r.room_code = 'R9' WHERE c.slug = 'wolfhouse-somo' ON CONFLICT (client_id, bed_code) DO NOTHING;
INSERT INTO beds (client_id, room_id, bed_code, bed_number, bed_label, planning_row_label, active, sellable) SELECT c.id, r.id, 'R9-B6', 6, 'Bed 6', 'R9 - Bed 6', TRUE, TRUE FROM clients c JOIN rooms r ON r.client_id = c.id AND r.room_code = 'R9' WHERE c.slug = 'wolfhouse-somo' ON CONFLICT (client_id, bed_code) DO NOTHING;
INSERT INTO beds (client_id, room_id, bed_code, bed_number, bed_label, planning_row_label, active, sellable) SELECT c.id, r.id, 'R10-B1', 1, 'Bed 1', 'R10 - Bed 1', TRUE, TRUE FROM clients c JOIN rooms r ON r.client_id = c.id AND r.room_code = 'R10' WHERE c.slug = 'wolfhouse-somo' ON CONFLICT (client_id, bed_code) DO NOTHING;
INSERT INTO beds (client_id, room_id, bed_code, bed_number, bed_label, planning_row_label, active, sellable) SELECT c.id, r.id, 'R10-B2', 2, 'Bed 2', 'R10 - Bed 2', TRUE, TRUE FROM clients c JOIN rooms r ON r.client_id = c.id AND r.room_code = 'R10' WHERE c.slug = 'wolfhouse-somo' ON CONFLICT (client_id, bed_code) DO NOTHING;
INSERT INTO beds (client_id, room_id, bed_code, bed_number, bed_label, planning_row_label, active, sellable) SELECT c.id, r.id, 'R10-B3', 3, 'Bed 3', 'R10 - Bed 3', TRUE, TRUE FROM clients c JOIN rooms r ON r.client_id = c.id AND r.room_code = 'R10' WHERE c.slug = 'wolfhouse-somo' ON CONFLICT (client_id, bed_code) DO NOTHING;
INSERT INTO beds (client_id, room_id, bed_code, bed_number, bed_label, planning_row_label, active, sellable) SELECT c.id, r.id, 'R10-B4', 4, 'Bed 4', 'R10 - Bed 4', TRUE, TRUE FROM clients c JOIN rooms r ON r.client_id = c.id AND r.room_code = 'R10' WHERE c.slug = 'wolfhouse-somo' ON CONFLICT (client_id, bed_code) DO NOTHING;
INSERT INTO beds (client_id, room_id, bed_code, bed_number, bed_label, planning_row_label, active, sellable) SELECT c.id, r.id, 'R10-B5', 5, 'Bed 5', 'R10 - Bed 5', TRUE, TRUE FROM clients c JOIN rooms r ON r.client_id = c.id AND r.room_code = 'R10' WHERE c.slug = 'wolfhouse-somo' ON CONFLICT (client_id, bed_code) DO NOTHING;
INSERT INTO beds (client_id, room_id, bed_code, bed_number, bed_label, planning_row_label, active, sellable) SELECT c.id, r.id, 'R10-B6', 6, 'Bed 6', 'R10 - Bed 6', TRUE, TRUE FROM clients c JOIN rooms r ON r.client_id = c.id AND r.room_code = 'R10' WHERE c.slug = 'wolfhouse-somo' ON CONFLICT (client_id, bed_code) DO NOTHING;

-- Bookings/conversations/messages: import via db:sync
COMMIT;
