'use strict';
const assert = require('node:assert/strict');
const {chromium} = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const fs = require('node:fs');
const path = require('node:path');
(async()=>{
  const target = process.env.PREVIEW_URL || 'http://127.0.0.1:18710/staff/login';
  const output = process.env.PREVIEW_EVIDENCE || path.join(__dirname,'evidence');
  fs.mkdirSync(output,{recursive:true});
  const browser = await chromium.launch({headless:true});
  const ctx = await browser.newContext({viewport:{width:1440,height:1000}});
  const page = await ctx.newPage(); const errors=[]; const unexpected=[];
  page.on('pageerror',e=>errors.push(e.message));
  page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
  page.on('request',r=>{if(!r.isNavigationRequest() && !r.url().startsWith('data:'))unexpected.push({url:r.url(),method:r.method()});});
  try{
    const response=await page.goto(target); assert.equal(response.status(),200);
    assert.equal(await page.locator('input[type=password]').count(),0);
    assert.match(await page.locator('body').innerText(),/sample data/i);
    await page.screenshot({path:path.join(output,'desktop.png'),fullPage:true});
    assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
    await page.locator('[data-session="0"]').click();
    assert.equal(await page.locator('#detail').isVisible(),true);
    await page.getByRole('button',{name:'Close booking details'}).click();
    await page.locator('[data-day="1"]').click();
    assert.match(await page.locator('main').innerText(),/Sunday, 6 September/);
    await page.locator('[data-today]').click();
    await page.locator('input[type=checkbox]').first().check();
    assert.equal(await page.locator('input[type=checkbox]').first().isChecked(),true);
    await page.locator('[data-page="inbox"]').click();
    await page.locator('#search').fill('Milo');
    assert.equal(await page.locator('[data-person]:visible').count(),1);
    await page.locator('[data-person="1"]').click();
    await page.locator('#draft').fill('A local-only draft edit');
    await page.locator('[data-person="0"]').click();
    await page.locator('[data-person="1"]').click();
    assert.equal(await page.locator('#draft').inputValue(),'A local-only draft edit');
    assert.equal(await page.getByRole('button',{name:'Send unavailable'}).isDisabled(),true);
    await page.locator('[data-reset-draft]').click();
    assert.notEqual(await page.locator('#draft').inputValue(),'A local-only draft edit');
    await page.screenshot({path:path.join(output,'inbox-desktop.png'),fullPage:true});
    await page.locator('[data-page="bookings"]').click();
    assert.equal(await page.locator('tbody tr').count(),6);
    await page.locator('[data-session="2"]').click();
    assert.match(await page.locator('#detailTitle').innerText(),/Find your flow/);
    await page.keyboard.press('Escape');
    await page.locator('[data-page="admin"]').click();
    assert.equal(await page.locator('.catalog article').count(),3);
    await page.getByRole('button',{name:'Preview settings'}).first().click();
    assert.match(await page.locator('#toast').innerText(),/No real price/);
    await page.screenshot({path:path.join(output,'admin-desktop.png'),fullPage:true});
    await page.locator('[data-page="schedule"]').click();
    await page.setViewportSize({width:390,height:844});
    await page.screenshot({path:path.join(output,'mobile.png'),fullPage:true});
    assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
    assert.deepEqual(errors,[]); assert.deepEqual(unexpected,[]);
    console.log(JSON.stringify({result:'PASS',target,loginRemoved:true,desktopNoOverflow:true,mobileNoOverflow:true,consoleErrors:errors,subrequests:unexpected,evidence:output}));
  }finally{await ctx.close();await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
